print(" ------------------------------------------------")
print("|                                                |")
print("|    03GoodbyePerson                             |")
print("|    Name : Leo                                  |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello")
username = input("What is your name ?")
print("Goodbye" + username)