print(" ------------------------------------------------")
print("|                                                |")
print("|    04GoodTeacher                               |")
print("|    Name : Leo                                  |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
username = input("Teacher's name (try MrHoran)")
print(username + " is an ok teacher")