print(" ------------------------------------------------")
print("|                                                |")
print("|    02GoodbyeWorld                              |")
print("|    Name : Leo                                  |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello World")
input("Press Enter to continue...")
print("Goodbye World")