import os 
clearConsole = lambda : os.system("cls")
def helloworld():
    print(" ")
    print("----Start of Output ---------------------------")
    print(" ")
    print("Hello World")
    print(" ")
    print("----End of Output -----------------------------")
    print(" ")
    print(" ")
    print(" ")
    input("Press enter to continue")
def goodbyeworld():
    print(" ")
    print("----Start of Output ---------------------------")
    print(" ")
    print("Hello World")
    input("------> Program paused - press enter to continue")
    print("Goodbye World")
    print(" ")
    print("----End of Output -----------------------------")
    print(" ")
    print(" ")
    print(" ")
    input("Press enter to continue")
def goodbyeperson():
    print(" ")
    print("----Start of Output ---------------------------")
    print(" ")
    print("Hello")
    username = input("What is your name ? ")
    print("Goodbye " + username)
    print(" ")
    print("----End of Output -----------------------------")
    print(" ")
    print(" ")
    print(" ")
    input("Press enter to continue")
def goodteacher():
    print(" ")
    print("----Start of Output ---------------------------")
    print(" ")
    x = input("Teacher's name (try Mr Horan) ")
    y = "Mr Horan"
    if x == y:
        print ("You are lucky, he is a great teacher.")
    else:
        print(x + " is an ok teacher")
    print(" ")
    print("----End of Output -----------------------------")
    print(" ")
    print(" ")
    print(" ")
    input("Press enter to continue")
def forloop():
    print(" ")
    print("----Start of Output ---------------------------")
    print(" ")
    for x in range(1, 500):
        print(x)
    print(" ")
    print("----End of Output -----------------------------")
    print(" ")
    print(" ")
    print(" ")
    input("Press enter to continue")
def whileloop():
    print(" ")
    print("----Start of Output ---------------------------")
    print(" ")
    i = input("What is the name of this subject ")
    while i != "IST":
        print("Not Correct - try again")
        i = input("What is the name of this subject ")
    print(" ")
    print(" ")
    print(" Congratulations!!")
    print(" ")
    print(" ")
    print("----End of Output -----------------------------")
    print(" ")
    print(" ")
    print(" ")
    input("Press enter to continue")
def exit():
    print(" ")
    print("----Start of Output ---------------------------")
    print(" ")
    print("----End of Output -----------------------------")
    print(" ")
    print(" ")
    print(" ")
    input("Press Enter to continue ")
    quit()
def menu():
    clearConsole()
    print(" ------------------------------------------------")
    print("|                                                |")
    print("|    07Menu                                      |")
    print("|    Name : Leo                                  |")
    print("|    Version : 01                                |")
    print("|                                                |")
    print(" ------------------------------------------------")
    print(" ")
    print("1. Hello World ")
    print("2. Goodbye World ")
    print("3. Goodbye Person ")
    print("4. Good Teacher ")
    print("5. forLoop ")
    print("6. whileLoop ")
    print("7. string Loop ")
    print("8. Convert to ascii ")
    print("9. Encode a string ")
    print("x. To Exit ")
menu()
a = input("Enter an option ")
while a != "x":
    if a == "1":
        helloworld()
    elif a =="2":
        goodbyeworld()
    elif a =="3":
        goodbyeperson()
    elif a =="4":
        goodteacher()
    elif a =="5":
        forloop()
    elif a =="6":
        whileloop()      
    else:
        print(" ")
        print("----Start of Output ---------------------------")
        print(" ")
        print("invalid option")
        print(" ")
        print("----End of Output -----------------------------")
        print(" ")
        print(" ")
        print(" ")
        input("Press enter to continue")
    clearConsole()
    menu()
    a = input("Enter an option ")       
print(" ")
print("----Start of Output ---------------------------")
print(" ")
print("----End of Output -----------------------------")
print(" ")
print(" ")
print(" ")
input("Press Enter to continue ")
quit()
