print(" ------------------------------------------------")
print("|                                                |")
print("|    06HelloWorld                                |")
print("|    Name : Leo                                  |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
i = input("What is the name of this subject ")
while i != "IST":
  print("Not Correct - try again")
  i = input("What is the name of this subject ")
print("")
print("")
print(" Congratulations!!")
print("")
print("")
print("")
